### ISSUE TITLE
release?

### ISSUE THREAD

**Issue by zimbatm** [alexcrichton/cargo-local-registry#11]
Hi, do you mind cutting another release with the deterministic build fix from #10? It would help us bootstrap rust and cargo at https://github.com/NixOS/nixpkgs/pull/30088

**Comment by alexcrichton** [comment]
Sure!

**Comment by zimbatm** [comment]
thanks! are you going to publish the binaries as well?

**Comment by alexcrichton** [comment]
I just pushed a new tag which I think fixes that

**Comment by zimbatm** [comment]
Brilliant, thanks a lot!
