### ISSUE TITLE
Feature request: include non-crates dependencies

### ISSUE THREAD

**Issue by MarkSwanson** [alexcrichton/cargo-local-registry#4]
I'm investigating using cargo-local-registry to help with our Rust PCI compliance story.

Unfortunately - because of immutable and insurmountable restrictions in our build network - cargo can't connect to the PCI compliant git repo that holds some dependencies.

What would (I think) work perfectly for us is if cargo-local-registry copied all dependencies, not just the ones from crates.io.

Is this a possibility?

Thanks!

Edit: we're looking into creating our own PCI compliant version of crates.io that we run internally that:
- reads in updates from crates.io
- integrates with our PCI compliant git repo so corporate developers can push their crates to a corporate crates.io that will be available to our PCI compliant build systems.

It's a lot of work and we were hoping cargo-local-registry could somehow be made to work to tide us over.

We'd be happy to do most of the work with some guidance/mentoring - if you think it's feasible.

Thanks again.

**Comment by alexcrichton** [comment]
In general this crate is intended for vendoring crates, not arbitrary dependencies. This sounds like a problem for the relevant build scripts, not for cargo-local-registry?
